spring.application.name=student


spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://localhost:5432/bd
#spring.datasource.username=postgres
#spring.datasource.password=postgres
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML5

# Base64-encoded AES key
app.crypto.key=${APP_CRYPTO_KEY:leUWZS51gzbZX25QuZcGVQ+LjBoER03ITCaKkzjKyc0=}


spring.jpa.show-sql=true
logging.level.sql=debug